from playwright.sync_api import expect


def check_visual_effects(browser, base, artifacts):
    context = browser.new_context(viewport={'width': 1440, 'height': 1000}, reduced_motion='no-preference')
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(base)
    visual = page.locator('.network-visual')
    expect(visual).to_be_visible()
    expect(visual).to_have_class('network-visual is-animating')
    visual.get_by_role('button', name='네트워크 모션 정지').focus()
    page.keyboard.press('Enter')
    expect(visual.get_by_role('button', name='네트워크 모션 재생')).to_be_visible()
    assert visual.evaluate("el => el.getAnimations({subtree: true}).every(animation => animation.playState === 'paused')")
    page.evaluate("window.scrollTo({top: document.body.scrollHeight, behavior: 'instant'})")
    page.wait_for_function("getComputedStyle(document.getElementById('reading-progress')).transform === 'matrix(1, 0, 0, 1, 0, 0)'")
    page.evaluate("window.scrollTo({top: 0, behavior: 'instant'})")
    expect(visual.get_by_role('button', name='네트워크 모션 재생')).to_be_visible()
    visual.get_by_role('button', name='네트워크 모션 재생').click()
    expect(visual).to_have_class('network-visual is-animating')
    page.locator('#skills').scroll_into_view_if_needed()
    expect(visual).to_have_class('network-visual')
    page.evaluate("window.scrollTo({top: 0, behavior: 'instant'})")
    expect(visual).to_have_class('network-visual is-animating')
    page.emulate_media(reduced_motion='reduce')
    expect(visual.get_by_role('button', name='네트워크 모션 꺼짐')).to_be_disabled()
    assert visual.evaluate('el => el.getAnimations({subtree: true}).length === 0')
    expect(page.locator('#education .section-heading')).to_be_visible()
    page.emulate_media(reduced_motion='no-preference')
    expect(visual.get_by_role('button', name='네트워크 모션 정지')).to_be_enabled()
    for width in [1440, 768, 390, 320]:
        page.set_viewport_size({'width': width, 'height': 1000})
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
        page.locator('#profile').screenshot(path=str(artifacts / f'visual-profile-{width}.png'), animations='disabled')
    assert not errors, errors
    context.close()

    fallback = browser.new_context(reduced_motion='reduce')
    fallback.route('**/js/portfolio-effects.js', lambda route: route.abort())
    page = fallback.new_page()
    page.goto(base)
    expect(page.locator('#profile h1')).to_be_visible()
    expect(page.locator('#education')).to_be_visible()
    expect(page.locator('#skills')).to_be_visible()
    expect(page.locator('.network-visual')).to_have_count(0)
    fallback.close()
    print('PASS: visual motion pause/resume, keyboard, reduced motion, off-screen pause, reading progress, responsive layout and content fallback.')
